FROM node:22-alpine as production

USER node
WORKDIR /usr/src/app

COPY --chown=node:node . .

RUN yarn install
RUN yarn build


FROM production as api
CMD ["yarn", "start:api"]


FROM production as scraper
CMD ["yarn", "start:scraper"]
